name: Algoriths repo Actions Test
run-name: ${{github.actor}} , Testing out github actions
on : [push]
jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out Repo
        uses: actions/checkout@v3

      - name: Linting C++ files
        uses: cpp-linter/cpp-linter-action@v2

      - name: Build C++ project
        uses: nicledomaS/cmake_build_action@v1.4
        with:
          submodule_update: ON
          run_tests: ON
          unit_test_build: -Dtest=ON
          create_package: ON
        env:
          DEFAULT_BRANCH: main
